name: "Terraform Init"
description: "Terraform Init Composite Action"
inputs:
  tf-version:
    required: true
    description: "Terraform Version"
  aws-region:
    required: true
    description: "AWS Region"
  terraform-wrapper:
    required: true
    description: "Terraform Wrapper"
  terraform-execution-iam-role-arn:
    required: false
    description: "Terraform Execution IAM Role ARN"
runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.tf-version }}
        terraform_wrapper: ${{ inputs.terraform-wrapper }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.terraform-execution-iam-role-arn }}
        aws-region: ${{ inputs.aws-region }}
        role-duration-seconds: 1200
    - name: Terraform init
      id: tfinit
      shell: bash
      run: terraform init -upgrade -migrate-state
      working-directory: ${{ inputs.working-direcory }}

