name: "Terraform Plan"
description: "Terraform Plan Composite Action"
inputs:
  deploy:
    required: true
    description: "Desired state for the deployment. true=deploy | false=destroy"
  aws-region:
    required: true
    description: "AWS Region"
  init-outcome:
    required: true
    description: "Terraform init command outcome"
  extra-args:
    required: false
    description: "Terraform plan command extra arguments"
outputs:
  exitcode:
    description: "Terraform Plan Exit code"
    value: ${{ steps.plan.outputs.exitcode }}
runs:
  using: "composite"
  steps:
    - name: Terraform Format and style
      id: fmt
      continue-on-error: true
      working-directory: terraform
      shell: bash
      run: terraform fmt -check -diff -recursive
    - name: Terraform Validate
      id: validate
      working-directory: terraform
      continue-on-error: true
      shell: bash
      run: terraform validate -no-color
    - name: Define Terraform Plan Command # 'terraform plan' or 'terraform plan -destroy'
      id: tf_plan_command
      working-directory: terraform
      shell: bash
      run: |
        if ${{ inputs.deploy }}
        then
          echo "PLAN_COMMAND=terraform plan" >> $GITHUB_OUTPUT
        else
          echo "PLAN_COMMAND=terraform plan -destroy" >> $GITHUB_OUTPUT
        fi
    - name: Add extra arguments mask
      if: ${{ inputs.extra-args != '' }}
      shell: bash
      run: echo "::add-mask::${{ inputs.extra-args }}"
    - name: Terraform Plan
      id: plan
      working-directory: terraform
      continue-on-error: true
      shell: bash
      run: |
        ${{ steps.tf_plan_command.outputs.PLAN_COMMAND }} \
          -no-color \
          -detailed-exitcode \
          -input=false \
          ${{ inputs.extra-args }} | tee plan.out
    #new code here
    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: terraform/plan.tfout #you can adapt the path to your terraform plan file

    - name: Copy .terraform.lock.hcl to workspace
      shell: bash
      run: cp terraform/.terraform.lock.hcl /home/runner/work/sunnytoorzaizi/githubworkflows/terraform/.terraform.lock.hcl

    - name: Upload .terraform.lock.hcl
      uses: actions/upload-artifact@v3
      with:
        name: terraform-workspace
        path: /home/runner/work/sunnytoorzaizi/githubworkflows/terraform/.terraform.lock.hcl
        include-hidden-files: true
    #new code ends here
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      shell: bash
      run: exit 1