name: Terraform Reusable

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
#   pull-requests: write # This is required to add comments to Pull Requests
#   deployments: write # This is required to deactivate deployments

on:
  workflow_call:
    inputs:
      tf-version:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      terraform-execution-iam-role-arn:
        required: true
        type: string
      terraform-wrapper:
        required: true
        type: boolean
      deploy:
        required: true
        type: boolean
      working-directory:
        required: true
        type: string



defaults:
    run:
      shell: bash

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout composite actions
        uses: actions/checkout@v4
        with:
          repository: sunnytoorzaizi/githubworkflows
          path: composite
      - name: Terraform Init
        id: init
        uses: ./composite/.github/actions/terraform-init
        with:
          tf-version: ${{ inputs.tf-version }}
          aws-region: ${{ inputs.aws-region }}
          terraform-wrapper: ${{ inputs.terraform-wrapper }}
          terraform-execution-iam-role-arn: ${{ inputs.terraform-execution-iam-role-arn }}
      - name: Terraform Plan
        id: plan
        uses: ./composite/.github/actions/terraform-plan
        with:
          deploy: ${{ inputs.deploy }}
          aws-region: ${{ inputs.aws-region }}
          init-outcome: ${{ steps.init.outputs.outcome }}

  terraform-apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout composite actions
        uses: actions/checkout@v4
        with:
          repository: sunnytoorzaizi/githubworkflows
          path: composite
      - name: Terraform Init
        id: init
        uses: ./composite/.github/actions/setup-worker
        with:
          tf-version: ${{ inputs.tf-version }}
          aws-region: ${{ inputs.aws-region }}
          terraform-wrapper: ${{ inputs.terraform-wrapper }}
          terraform-execution-iam-role-arn: ${{ inputs.terraform-execution-iam-role-arn }}
      # - name: List dir contents 
      #   id: list-contents
      #   working-directory: terraform
      #   shell: bash
      #   run: ls -al
      - name: Terraform Apply
        id: apply
        uses: ./composite/.github/actions/terraform-apply
        with:
          deploy: ${{ inputs.deploy }}
          aws-region: ${{ inputs.aws-region }}
          init-outcome: ${{ steps.init.outputs.outcome }}