name: Terraform Workflow

on:
  push:
    branches:
      - main  # Or your desired branch
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.4 # specify your desired version

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        continue-on-error: true

      - name: Create Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        if: steps.plan.outcome == 'failure'
        with:
          name: terraform-plan
          path: tfplan

      - name: Terraform Apply
        id: apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.plan.outcome != 'failure'
        run: terraform apply -auto-approve tfplan