name: Terraform Reusable

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
#   pull-requests: write # This is required to add comments to Pull Requests
#   deployments: write # This is required to deactivate deployments

on:
  workflow_call:
    inputs:
      tf-version:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      terraform-execution-iam-role-arn:
        required: true
        type: string
      terraform-wrapper:
        required: true
        type: boolean
      deploy:
        required: true
        type: boolean
      working-directory:
        required: true
        type: string



defaults:
    run:
      shell: bash

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout composite actions
        uses: actions/checkout@v4
        with:
          repository: sunnytoorzaizi/githubworkflows
          path: composite
      - name: Terraform Init
        id: init
        uses: ./composite/.github/actions/terraform-init
        with:
          tf-version: ${{ inputs.tf-version }}
          aws-region: ${{ inputs.aws-region }}
          terraform-wrapper: ${{ inputs.terraform-wrapper }}
          terraform-execution-iam-role-arn: ${{ inputs.terraform-execution-iam-role-arn }}
          working-directory: ${{ inputs.working-directory }}
      - name: Terraform Plan
        id: plan
        uses: ./composite/.github/actions/terraform-plan
        with:
          deploy: ${{ inputs.deploy }}
          aws-region: ${{ inputs.aws-region }}
          init-outcome: ${{ steps.init.outputs.outcome }}
          working-directory: ${{ inputs.working-directory }}

  manual-approval:
      name: manual approval
      runs-on: ubuntu-latest
      needs: terraform-plan
      if: success()

      permissions:
        issues: write
        contents: read

      steps:
        - name: Await for manual approval
          uses: trstringer/manual-approval@v1
          with:
            secret: ${{ github.TOKEN }}
            approvers: sunnytoorzaizi , fghauri-zaizi #add the usernames of the users who can approve the deployment
            minimum-approvals: 1 #specify the number of approvals needed
            issue-title: "Manual Approval Required for Terraform Apply"
            issue-body: "Please approve or deny the deployment."
            exclude-workflow-initiator-as-approver: false

  terraform-apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    needs: manual-approval
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout composite actions
        uses: actions/checkout@v4
        with:
          repository: sunnytoorzaizi/githubworkflows
          path: composite
      - name: Terraform Init
        id: init
        uses: ./composite/.github/actions/terraform-init
        with:
          tf-version: ${{ inputs.tf-version }}
          aws-region: ${{ inputs.aws-region }}
          terraform-wrapper: ${{ inputs.terraform-wrapper }}
          terraform-execution-iam-role-arn: ${{ inputs.terraform-execution-iam-role-arn }}
          working-directory: ${{ inputs.working-directory }}
      - name: Terraform Apply
        id: apply
        uses: ./composite/.github/actions/terraform-apply
        with:
          deploy: ${{ inputs.deploy }}
          aws-region: ${{ inputs.aws-region }}
          init-outcome: ${{ steps.init.outputs.outcome }}
          working-directory: ${{ inputs.working-directory }}